#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Feb 02 17:48:53 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=Bliss-Shader-older.zip
